### ISSUE TITLE
Improvements on the structure of the project

### ISSUE THREAD

**Issue by lucasximenes** [PaMeirelles/TSP-MetaHeuristics#1]
I'll start off listing some changes that I believe should be implemented even if my other suggestions don't pan out:

- Add typing to all function arguments and function returns, as well as containers, such as vector, sets, etc.
- perform_swap should **only** perform the swap, I think calculation should be a separate function, this in turn allows you to test the swap beforehand, and only swap if necessary.

Now, some ideas:

- I believe there should be a separated file for a new struct called Solution, which contains the path and it's cost, the auxiliary functions for calculating costs and whatnot, as well as all the local search manipulations for a solution, such as swap, 2-opt, and so on.
- Get rid of modules?
- remaining_nodes in basic_greedy doesn't have to be a set, a simple vector/array does the job

Lastly some nitpicks:

- All file names must be PascalCase
- All function, struct and module names must be camelCase

**Comment by PaMeirelles** [comment]
Implemented some of the more basic changes:

- ~~Add typing to all function arguments and function returns, as well as containers, such as vector, sets, etc.~~
- perform_swap should only perform the swap, I think calculation should be a separate function, this in turn allows you to test the swap beforehand, and only swap if necessary.
- I believe there should be a separated file for a new struct called Solution, which contains the path and it's cost, the auxiliary functions for calculating costs and whatnot, as well as all the local search manipulations for a solution, such as swap, 2-opt, and so on.
- Get rid of modules?
- ~~remaining_nodes in basic_greedy doesn't have to be a set, a simple vector/array does the job~~
- ~~All file names must be PascalCase~~
- ~~All function, struct and module names must be camelCase~~

**Comment by rafaelmartinelli** [comment]
My two cents:

- "Add typing to all function arguments and function returns" is needed in Julia. It is actually asked by the language developers, to improve efficiency.
- "`perform_swap` should only perform the swap": The way we usually do is each neighborhood with three functions: `evaluate`, `move`, and `localSearch`. The first one just returns the cost change, the second just changes the solution, and the third is the local search.
- "I believe there should be a separated file for a new struct called Solution": Since I still think in OO, I believe each element should have a separate file with its struct. Like Swap.jl, with a `struct Swap`, containing the input data, and any "attributes". All functions in this file should be `function blah(swap::Swap, ...)`. But anyway, I accept suggestions...
- "Get rid of modules": That's a common mistake in Julia. At start, it seems everything will be modules, but they're actually quite painful to use. We usually only create modules for "finished" code, i.e., code we won't change in the future.
- "`remaining_nodes` in `basic_greedy` doesn't have to be a set, a simple vector/array does the job": this one we have to talk about. As @lucasximenes said, in optimization, you'll use anything than contiguous memory (vectors, arrays) in a very few situations. In this case, being a constructive heuristic (not the bottleneck), it's ok to use. But otherwise, it's always array.
- "All file names must be PascalCase", "All function, struct and module names must be camelCase": In Julia's standard, almost everything is snake_case. I think only structs are PascalCase. And I hate it. The most accepted code style is almost what @lucasximenes wrote, it's Java's style. Types (structs, modules and files) are PascalCase, functions are camelCase, and variables can be camelCase or snake_case (but choose one and use it everywhere - I prefer camelCase).

Those are my huge two cents... 😆

**Comment by PaMeirelles** [comment]
> "I believe there should be a separated file for a new struct called Solution": Since I still think in OO, I believe each element should have a separate file with its struct. Like Swap.jl, with a struct Swap, containing the input data, and any "attributes". All functions in this file should be function blah(swap::Swap, ...). But anyway, I accept suggestions...

What are your thoughts on this structure?

```
struct Solution{R, C, H}
    Representation::R
    Cost::C
    Evaluate::Function # A function that takes a single argument of type H and returns C
    Move::Function     # A function that takes a tuple (H, R) and returns R
    LocalSearch::Function # A function that takes a tuple (R, C) and returns a tuple (R, C)
end
```

In our current scenario, R would be an array of integers, C would be an integer, and H might be a struct of type Swap as suggested. Unfortunately, we can't enforce the signatures of Evaluate, Move, and LocalSearch in Julia. However, I believe this interface is versatile enough for us to experiment with various Representations and Changes while also accommodating other problems.

**Comment by rafaelmartinelli** [comment]
I'm not sure if the functions should be in the solution. Usually I do an organization like this:

```julia
struct Solution
    route::Vector{Int64}
    cost::Int64
end
```

```julia
struct Swap
   data::TSP
   solution::Solution
end

function eval(swap::Swap, pos1::Int64, pos2::Int64)::Int64
    (...)
end

function move!(swap::Swap, pos1::Int64, pos2::Int64)
    (...)
end

function localSearch!(swap::Swap)::Bool
    (...)
end
```

Maybe we could do an abstract struct for Neighborhood, like:

```julia
abstract struct Neighborhood end
```

and then every neighborhood would be:

```julia
struct Swap <: Neighborhood
    (...)
end
```

**Comment by lucasximenes** [comment]
2 details about this commit, I believe there should be an auxiliary function in the `Solution.jl` file that receives a path and returns the cost of said path, that way the `eval` function in `Swap.jl` becomes way cleaner. The other detail is that, in order to make things simpler, I fixed the first and last positions of a solution in the `firstImprovement!` subroutine, which is suboptimal, I believe. So that has to be fixed.
